# Generated by Django 5.2.8 on 2025-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Optional profile picture', null=True, upload_to='profile_images/'),
        ),
    ]
 
