# Generated by Django 4.2.27 on 2026-01-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_classes_2009', models.FloatField(help_text='Number of classes in the institution', verbose_name='Number of Classes (2009)')),
                ('eleves_premier', models.FloatField(help_text='Number of primary/elementary students', verbose_name='Primary Students')),
                ('eleves_superieur', models.FloatField(help_text='Number of secondary/higher education students', verbose_name='Secondary Students')),
                ('latitude', models.FloatField(help_text='Geographic latitude', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Geographic longitude', verbose_name='Longitude')),
                ('cluster', models.IntegerField(help_text='Assigned cluster number (0-3)', verbose_name='Cluster')),
                ('name', models.CharField(blank=True, help_text='Optional name for the institution', max_length=255, null=True, verbose_name='Institution Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['-created_at'],
            },
        ),
    ]
 
